# Generated by Django 2.1.7 on 2019-02-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0002_auto_20190223_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readSensor1', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='source1',
            name='reading1',
            field=models.FloatField(default=0.0),
        ),
    ]
