# Generated by Django 2.1.7 on 2019-02-24 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0003_auto_20190223_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='source1',
            name='time1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='time1lvl',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 3, 37, 40, 982726, tzinfo=utc), verbose_name='auto_now_add = True, blank = False, date published'),
            preserve_default=False,
        ),
    ]
