# Generated by Django 2.1.7 on 2019-02-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0004_auto_20190223_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterlevel',
            old_name='readSensor1',
            new_name='reading1',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='time1lvl',
            new_name='time1',
        ),
    ]
