# Generated by Django 2.1.7 on 2019-04-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0007_result_generator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension_details',
            old_name='reading1',
            new_name='shoesize',
        ),
        migrations.RenameField(
            model_name='dimension_details',
            old_name='reading2',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='dimension_details',
            old_name='reading3',
            new_name='width',
        ),
    ]
