# Generated by Django 2.1.7 on 2019-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0008_auto_20190409_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOfQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
