# Generated by Django 2.1.7 on 2019-04-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0009_resultofquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('shoesize', models.FloatField(default=0.0)),
                ('result', models.CharField(max_length=32)),
                ('time1', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
