# Generated by Django 2.1.7 on 2019-04-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0010_predictivemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictivemodel',
            name='result',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
