# Generated by Django 2.1.7 on 2019-04-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0011_auto_20190410_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterTweetDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tweet', models.CharField(editable=False, max_length=280)),
                ('result', models.CharField(editable=False, max_length=100)),
                ('NumOfTweets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebScrapeForTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
