# Generated by Django 2.1.7 on 2019-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomingData', '0012_entertweetdatas_webscrapefortweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertweetdatas',
            name='NumOfTweets',
        ),
        migrations.AddField(
            model_name='entertweetdatas',
            name='email',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entertweetdatas',
            name='name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webscrapefortweet',
            name='NumOfTweets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webscrapefortweet',
            name='Tweet',
            field=models.CharField(editable=False, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='webscrapefortweet',
            name='result',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entertweetdatas',
            name='Tweet',
            field=models.CharField(blank=True, editable=False, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='entertweetdatas',
            name='result',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
